# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
de:
  languageCode: de-de
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/de

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en-us
  contentDir: content/en
  title: Prof. Dr. Dominik Vogel
  params:
    description: Assistant Professor of Public Management
  menu:
    main:
      - name: Home
        url: '#about'
        weight: 1
